BookPOC/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookPOC.Repository;
using BookPOC.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BookPOC.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookRepository _bookRepository;
        private readonly ICategoryRepository _categoryRepository;

        public BookController(IBookRepository bookRepository, ICategoryRepository categoryRepository)
        {
            _bookRepository = bookRepository;
            _categoryRepository = categoryRepository;
        }

        public IActionResult List()
        {
            var booksListViewModel = new BookListViewModel
            {
                Books = _bookRepository.GetAllBooks()
            };

            return this.View(booksListViewModel);
        }

        public IActionResult Detail(int id)
        {
            var book = _bookRepository.GetBookById(id);
            if (book == null)
                return NotFound();

            return this.View(book);
        }
    }
}

BookPOC/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace BookPOC.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

BookPOC/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookPOC.Models;
using BookPOC.Repository;
using BookPOC.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BookPOC.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly IBookRepository _bookRepository;
        private readonly ShoppingCart _shoppingCart;

        public ShoppingCartController(IBookRepository bookRepository, ShoppingCart shoppingCart)
        {
            _bookRepository = bookRepository;
            _shoppingCart = shoppingCart;
        }

        public IActionResult Index()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;
            var shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(shoppingCartViewModel);
        }

        public RedirectToActionResult AddToShoppingCart(int id)
        {
            var book = _bookRepository.GetBookById(id);
            if (book != null)
            {
                _shoppingCart.AddToCart(book, 1);
            }

            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int id)
        {
            var book = _bookRepository.GetBookById(id);
            if (book != null)
            {
                _shoppingCart.RemoveFromCart(book);
            }

            return RedirectToAction("Index");
        }
    }
}

BookPOC/Views/Shared/_CardBook.cshtml
@model Book

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <h2>
            <a asp-controller="Book" asp-action="Detail" asp-route-id="@Model.Id">@Model.Name</a>

        </h2>
        <img src="@Model.ImageUrl" alt="" width="150" height="400">
        <div class="caption">
            <p>@Model.ShortDescription</p>
            <h3 class="pull-right">@Model.Price.ToString("c")</h3>
        </div>
        <div class="addToCart">
            <p class="button">
                <a class="btn btn-primary" asp-controller="ShoppingCart" asp-action="AddToShoppingCart" asp-route-id="@Model.Id">Add to cart</a>
            </p>
        </div>
    </div>
</div>

BookPOC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>E-Library</title>
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/fontawesome/css/all.css" rel="stylesheet" />
    <link href="~/contents/site.css" rel="stylesheet" />

</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-sm bg-primary navbar-dark">
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link active" asp-controller="Home" asp-action="Index">Home</a>
                    <a class="nav-item nav-link active" asp-controller="Book" asp-action="List">Books</a>
                    @await Component.InvokeAsync("ShoppingCartSummary")
                    <a class="nav-item nav-link active" asp-controller="Contact" asp-action="Index">Contact</a>
                </div>
            </div>
        </nav>
        <div class="row">
            @RenderBody()
        </div>
    </div>

    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
</body>
</html>